### ISSUE TITLE
M15 Plan

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1060]
This is the plan for the M15 milestone.

### Getting started
- [x] add a min version into the IntelliJ checks in flutter doctor #1054 @devoncarew
- [x] define and plan the IntelliJ getting started workflow #1095 @pq 
- [ ] 💪  redo wizard flow (stretch) 
  - [x] add the ability to install the flutter sdk from the new project wizard @pq
  - [x] display error messages from flutter create when project creation fails #1064

### Running and debugging
- [x] UX cleanup to the Flutter tool window toolbar #1024 @devoncarew
- [x] expose debugPaintBaselinesEnabled in the Flutter tool window #1025 @devoncarew
- [x] not enough feedback when a hot reload has been performed #939
- [x] support running tests via `flutter test` #66 @skybrian
- [x] enable starting an Android simulator from IntelliJ #536 @devoncarew

### Plugins and external IDE support
- [x] `packages get` doesn't handle nested packages #1092
- [x] open Xcode from a flutter app project #880 @pq

### Editing
- [x] request to show `@required` parameters first in code completion #1049 @pq
- [x] code completion w/ ternary args #1055 @pq

---

## Releasing
The release date is ~ June 30

- [x] update change notes @pq
- [x] create candidate build, June 27 @pq
- [ ] testing ([script](https://github.com/flutter/flutter-intellij/blob/master/testing.md)):
  - [x] run test script on internal build @jwren
  - [x] run test script on IntelliJ CE @pq
  - [ ] run test script on IntelliJ CE windows @mit-mit 
  - [x] run test script on WebStorm @devoncarew
- [x] publish plugin @pq
- [ ] send blog post @wmleler 

---

## Deferred

- project name validation for WebStorm #1059
- add ui to allow developers to configure the break on exceptions behavior #964 @devoncarew (landing upstream)
- improve "wrap with child" to add required params (like completions) #1052   
- fix and re-enable launching in profile (and release) mode(s) #930
- initial open inspector action #1104
- open Xcode from a flutter plugin project #1117
- open Android Studio from a Flutter app project #1063
- open Android Studio from a Flutter plugin project #1118
- locate sdks using the .packages file #1039
- confusion around `pub get` prompt #1026
- failed project creation leaves behind a directory with the invalid name #1058 

---

| Mark        | Description           | 
| ------------- |:-------------:|
| 🏃    | in progress |
| ✋     | blocked |
| 💪     | stretch |

**Comment by brianegan** [comment]
🎉 "Enable starting an Android simulator from IntelliJ" 🎉

**Comment by mit-mit** [comment]
FYI @pq @devoncarew I updated 'Plugins and external IDE support' to cover both app and plugin as discussed in #880

**Comment by pq** [comment]
We're published and Blog post is on the way.  🎉
