### ISSUE TITLE
[Meta] Project creation improvements.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1095]
A meta-issue to track various proposed improvements to the project creation flow.

Things we've actively discussed include:

* [ ] Validation as you type  --- besides improving UX, this would sidestep rogue file generation on creation failures #1058
* [ ] Project name proposals #1093
* [x] Affordances to trigger an SDK installation flow #764
* [ ] General reconsideration of the up-frontness of SDK config prompt #734
* [ ] Improved `flutter create` progress reporting #734
* [ ] General tidying up of unnecessary configuration options
* [ ] Nice branding (a la Android Studio)

As a first cut, we'd like to experiment with something trimmed down like

![image](https://user-images.githubusercontent.com/67586/26856250-91158c76-4ad7-11e7-946e-4c3f4d6d5054.png)

and add details as needed.

Down the road we could consider adding

* [ ] Template generation (a la stagehand) #1047
* [x] Plugin project support

**Comment by devoncarew** [comment]
assumed stale -
