### ISSUE TITLE
M16 Plan

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1153]
This is the plan for the M16 milestone.

### infra + architecture
- [x] add an action to restart the flutter daemon #1143
- [x] re-consider how we define flutterness for a module #748 @jwren 
- [x] locate sdks using the .packages file #1039
- [x] IntelliJ being open interferes with switching Flutter branches #1155

### running
- [x] have the run button active when there are no devices connected #971 @devoncarew
- [x] when the app hasn't fully started yet the play button should be disabled #1112 @devoncarew
- [x] have an option to enable reload-on-save #563 @devoncarew
- [x] support launching apps in profile and release modes #930

### testing
- [x] add editor annotations for running tests by name #1174 @pq
- [x] support for running widget tests #1181 @pq
- [x] project templates should include unit tests #1171 @pq

### plugin interop
- [x] IntelliJ should query flutter_tools for the Android sdk location #1150 @devoncarew

---

## Releasing
The release date is 7/28

- [x] update change notes @pq
- [x] create candidate build, 7/25 @pq
- [ ] testing ([script](https://github.com/flutter/flutter-intellij/blob/master/docs/testing.md)):
  - [ ] run test script on internal build @jwren
  - [x] run test script on IntelliJ CE @pq
  - [x] run test script on IntelliJ CE windows @mit-mit 
  - [x] run test script on WebStorm @devoncarew
- [x] publish plugin @pq
- [ ] send blog post @wmleler 
- [ ] re-merge https://github.com/flutter/website/pull/511 now that we fixed https://github.com/flutter/flutter-intellij/issues/930 @mit-mit 

---

## Deferred

- create an initial "Open inspector" action #1104 @pq, @jacob314
- show the frame times and effective fps in the flutter view #1144 @devoncarew
- initial work to support Android Studio (likely not landing in M16) #1186 @stevemessick 
- add test annotations to the structure view #1175 @pq
- project templates should include integration tests #1172 @pq
- ~~improve the open android emulator actions~~ #1136 (no action)

---

🏃 in progress, ✋ blocked, 💪 stretch
