### ISSUE TITLE
M17 Plan

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1248]
This is the plan for the M17 milestone.

### flutter view
- [x] create an initial "Open inspector" action #1104

### testing
- [x] Improve group support for widget tests #1249 @pq 🏃 

### run and reload
- [x] highlight analysis issues on app launch #729 @devoncarew
- [x] implement changes based on the hot reload on save feedback #1215
  - [x] ship hot reload on save
- [x] add analytics to measure the number of users using hot reload in their workflow (vs. full restart, or neither) @devoncarew

### getting started
- [x] improvements to the new project wizard (plugins, source code kind selection) #1262
- [x] support creating a new 'package' project #1291 @stevemessick 

---

## Releasing

The release date is ~7/31.

- [x] update change notes @pq
- [x] create candidate build @pq
- [ ] testing ([script](https://github.com/flutter/flutter-intellij/blob/master/docs/testing.md)):
  - [ ] run test script on internal build @jwren
  - [ ] run test script on IntelliJ CE @pq
  - [ ] run test script on IntelliJ CE windows @mit-mit 
  - [x] run test script on WebStorm @devoncarew
- [ ] publish plugin @pq
- [ ] send blog post @wmleler 

---

## Deferred

- provide a Flutter plugin for Android Studio (meta) #1186 @stevemessick 
- open Android Studio from a Flutter plugin project #1118
- open Xcode from a Flutter plugin project #1117

---

🏃 in progress, ✋ blocked, 💪 stretch
