### ISSUE TITLE
M18 Plan

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1315]
This is the plan for the M18 milestone.

### Editing
- [x] organization and programming language options not relevant for package project type #1304
- [x] show closing tags in build methods #1252 (landing upstream in the EAP Dart plugin)

### Running
- [x] for flutter launches, support passing in a `--flavor` param #1289
- [x] make reload on save the default #1331
- [x] analysis toast should provide a way to open the analysis view #1309
- [x] we should disallow a reload while another reload is taking place #1333

### Plugins
- [x] open Xcode from a Flutter plugin project #1117
- [x] open Android Studio from a Flutter plugin project #1118
- [x] open Android Studio from a Flutter app project #1063
- [x] show referenced flutter plugin in the project view #1090
- [x] support android studio #384 @stevemessick 

---

## Releasing

The release date is ~9/28.

- [x] update change notes @pq
- [x] create candidate build @pq
- [ ] testing ([script](https://github.com/flutter/flutter-intellij/blob/master/docs/testing.md)):
  - [ ] run test script on internal build @jwren
  - [x] run test script on IntelliJ CE @pq
  - [x] run test script on IntelliJ CE windows @mit-mit 
  - [x] run test script on Android Studio @stevemessick 
- [x] publish plugin @pq
- [ ] send blog post @wmleler 

---

## Deferred
- iron out issues around gradle and IDEA, and gradle+flutter+android studio (https://github.com/flutter/flutter/issues/9698 and https://github.com/flutter/flutter/issues/11632)
- in the 'is flutter module' check, we should also check the pubspec #1261 @jwren

---

🏃 in progress, ✋ blocked, 💪 stretch
