### ISSUE TITLE
M19 Plan

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1387]
This is the plan for the M19 milestone.

### Android Studio polish
Android Studio - address incoming issues, polish the integration @stevemessick @devoncarew
- [x] generated applicationId is wrongfully generated #1391

### bug fixes and backlog burndown
identify and address important issues in the backlog @pq @devoncarew
- [x] ensure vanilla dart tests are not misidentified as fluttery #1404
- [x] doing a full restart should re-focus the simulator to the foreground #1411
- [x] support IntelliJ 2017.3 EAP #1348
- [x] exclude errors in tests from blocking Reload on Save #1442
- [x] add the ability to run individual tests within groups #1439

### first shipping version of the inspector
- [x] ship the widget tree view of the inspector @jacob314
- [x] add a feedback link for the inspector preview #1418

---

## Releasing

The release date is ~11/9.

- [x] update change notes @pq
- [x] create candidate build @pq
- [ ] testing ([script](https://github.com/flutter/flutter-intellij/blob/master/docs/testing.md)):
  - [x] run test script on IntelliJ CE @pq
  - [x] run test script on Android Studio windows @devoncarew 
  - [ ] run test script on Android Studio @stevemessick 
  - [ ] run test script on internal build @jwren
  - [ ] run test script on IntelliJ CE EAP @devoncarew
- [ ] publish plugin @pq
- [ ] send blog post @wmleler 

---

## Deferred

- open in Android Studio action for a plugin project doesn't work #1372 
- review and polish the initial integration @jacob314 @pq (ongoing)
- investigation Android Studio's UI integration library @stevemessick (continuing)

---

🏃 in progress, ✋ blocked, 💪 stretch
