### ISSUE TITLE
M21

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1577]
This is the plan for the M21 milestone.

### Flutter Inspector
- [x] ship preview release

### Hot reload
- [x] wire into the flutter_tools protocol to get soft reload failure messages #1398

---

## Releasing

The release date is 1/5.

- [ ] update change notes @pq
- [ ] create candidate build @pq
- [ ] testing ([script](https://github.com/flutter/flutter-intellij/blob/master/docs/testing.md)):
  - [ ] run test script on IntelliJ CE @pq
  - [ ] run test script on Android Studio windows @devoncarew 
  - [ ] run test script on Android Studio @stevemessick 
  - [ ] run test script on internal build @jwren
  - [ ] run test script on IntelliJ CE EAP @devoncarew
- [ ] publish plugin @pq
- [ ] send blog post @wmleler 

---

## Deferred

- flutter plugin project is missing Android features #1482
- unable to resolve imports from Android Support Repository #966
- doctor doesn't report a flutter plugin in Android Studio #1438

---

🏃 in progress, ✋ blocked, 💪 stretch
