### ISSUE TITLE
[meta] Plugin Creation and Consumption

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1684]
## Make plugin creation great
- [ ] ensure that flutter projects can be opened in Android Studio as well-formed Android Studio projects #1525
- [ ] open in xCode action for a plugin project doesn't work #1373

## Make plugin consumption great
- [ ] make it easier to run the example app (delay until after M24)
