### ISSUE TITLE
[meta] Code Editing

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1685]
- [ ] have documentation around existing code editing assists [docs]
- [ ] improving discoverability of editing assists
- [ ] Flutter Preview or similar launched (M22, M23)
