### ISSUE TITLE
[journey] Understand and resolve layout issues

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1686]
- [x] source locations launched #1597
- [ ] UXR / usability study and incorporate feedback; or, measure success on CUJs?
  - [x] action item to define CUJ #1719
  - [x] hard to click on bottom of widget tree #1607
- [x] ensure we’re tracking the right analytics #1717
- [ ] docs written on flutter.io (and / or existing docs updated) [docs] #1718
- [ ] Visual property display in IntelliJ for all common padding, constraint, size, and font properties #1605 #1602
- [ ] polish UI for entering and exiting select mode https://github.com/flutter/flutter/issues/13837

**Comment by devoncarew** [comment]
@jacob314, @pq, can you review the above and add or adjust items? The goal for the meta issue is to track the work we want to have completed by M22, M23, and M24. Thanks!

**Comment by devoncarew** [comment]
closing in favor of more specific bugs and OKRs
