### ISSUE TITLE
[journey] Diagnose app memory usage

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1687]
- [ ] show memory usage using an on device widget (M22) #1701 
- [x] show memory usage in IntelliJ #1698
- [ ] provide web-based tooling to help users diagnose memory issues #1700
- ~link to the memory page from IntelliJ #1699~

**Comment by devoncarew** [comment]
closing in favor of more specific bugs and OKRs
