### ISSUE TITLE
[journey] Diagnose app UI jank / CPU usage

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1688]
- [x] link to the timeline view from IntelliJ #1702
- [x] review Flutter Inspector toolbar icons from the POV of perf debugging #1652
- [x] doc UI jank best practices and pitfalls #1703
