### ISSUE TITLE
testing M22

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1802]
This is a tracking issue to test the plugin release candidate for M22; the testing script is here: https://github.com/flutter/flutter-intellij/blob/master/docs/testing.md.

- [ ] 2017.3 /  2018.1 @devoncarew, @pq 
  - [x] @pq
  - [ ] @devoncarew 
- [ ] 2017.3 windows @mit-mit 
- [x] android studio 3.0 @stevemessick 
- [ ] IntelliJ internal @jwren 
- [ ] inspector @jacob314 

Please check off your line as you finish testing (and file any issues found).

**Comment by devoncarew** [comment]
(artifacts to be sent out shortly)
