### ISSUE TITLE
Logger view punchlist

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2340]
Some feedback from using the Logger view; feel free to break into separate issues:

- [x] when appending, the last item doesn't scroll into view (the last - 1 does)
- [x] it would be great if the text filter was live (filtering as you type, not just on return)
- [x] long text is truncated - we need to query the VM for the full value (which will be async, so we'll need to be careful to keep the original ordering of the log items) (#3052)
- [ ] we should display the 'error' and 'stackTrace' fields from dart:developer log() calls
- [x] we should have a way to display the severity (or at least, call out error level and warning level)
- [x] decide whether we do need to display the timestamp column (#2457)
- [x] we should devote more of the horizontal space to the message portion of the log entry (#2457)
- [x] stack traces don't look clickable, and don't jump to a location when clicked (#2402)
- [x] we should provide a visual separator after reloads and restarts (in the text console, we clear the console) (#2458)

/cc @pq

**Comment by devoncarew** [comment]
One more item; when run in Debug mode, the view has less horizontal space available to it:

<img width="1348" alt="screen shot 2018-06-19 at 7 33 01 pm" src="https://user-images.githubusercontent.com/1269969/41664514-c2e87184-745a-11e8-854c-b9613d58e85d.png">

Much of the text that I want to see (the log message text) is now off the screen. We should consider making the non-message portion of the log entry more compact. Some ideas are to remove the entry timestamp, to move the entry timestamp column to the right side of the view, to use icons instead of text labels for log severity, ...

**Comment by pq** [comment]
Awesome feedback.  Along these lines a few things I've been mulling over:

* how "sticky" should modifications be?  (IOW: if I hide a column once, should it stick to the next session?)
* would auto-hiding columns in narrow contexts be surprising?
* would it be odd to have different default layouts in run vs. debug views?

Input welcome!

**Comment by quangson91** [comment]
@pq @devoncarew for me, I think we should make two things:
1. Bring console as a TAB beside `Debugger` tab.
2. Make log message in FlutterLogTree can `wrap text` (I mean display full text in multiple lines).

**Comment by devoncarew** [comment]
> would auto-hiding columns in narrow contexts be surprising?

It would be great if the user didn't need to hide columns - if the default layout was one we thought they could run with.

**Comment by quangson91** [comment]
I would be great if we can make default layout like this one:

![flutter_log_console_tab](https://user-images.githubusercontent.com/6185205/41672774-ff85bffe-74e4-11e8-8f8c-7986ff25304b.gif)

**Comment by pq** [comment]
Having a separate tab is an interesting idea.  Our thinking was that it is often useful to see both at once since logging information complements debugging.  In any case, striving for a layout that makes this at least _possible_ is a good thing to strive towards.

**Comment by quangson91** [comment]
@pq, @devoncarew I'm trying to fixing `long text display on flutter log view`.

Currently, as I checked, the table cell render highly depends on `ColoredTableCellRenderer` (to make text render can have style/color), but I can't figure out how to make text `auto wrap`.

Do you have any suggestion for that problem?

**Comment by quangson91** [comment]
@devoncarew Thank you, I'm checking.

**Comment by quangson91** [comment]
@devoncarew @pq Do you have any suggestion how we can query to the Dart VM to get the full log.
I've checked but can't found the solution :|

**Comment by devoncarew** [comment]
Yup, on the vm service, you'll want to call the `getObject()` method. Given an String object that has a truncated string value, I believe that getObject() will return the full value.

https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#getobject

**Comment by quangson91** [comment]
Thank you, I will continue checking :)

**Comment by quangson91** [comment]
@devoncarew, @pq our log entry almost come from `ProcessHandler` callback.
as I check, we don't have any log come from VmService (calblack) :|

**Comment by pq** [comment]
> You can simulate this currently by adding import dart:developer; in a flutter app, and then in the app, call log('Foo bar');.

👍 

I'm playing with this right now.  (Specifically for platform channel communications.)

@quangson91: let me know and I can cc you w/ progress.

**Comment by quangson91** [comment]
@pq, yes, please.
I would like to know how it works.
Thanks!

**Comment by devoncarew** [comment]
Closing as this is related to the experimental logging view.
