### ISSUE TITLE
tracking issue for android studio based performance tooling

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2541]
@terrylucas, getting some thoughts down about what we need to do to productionize the Android Studio based performance tooling, the versions we'd want to roll out, and the order of items:

V1:
- [x] create a new place for the content as a tool window positioned on the bottom of the window
- [x] implement a memory view based on the current functionality
- [x] build system work to be able to build and ship against AS 3.2, 3.3, ...
- [ ] UX review (@InMatrix)
- [x] add class and instance tables

post V1:
- [x] determine how to handle multiple sessions
- [ ] determine if we should implement a CPU view

IntelliJ support is currently out of scope for V1; we can re-evaluate as we learn more from the implementation.

**Comment by terrylucas** [comment]
Features not implemented in DevTools have been re-created in the DevTools issues.

https://github.com/flutter/devtools/issues/465
