### ISSUE TITLE
fishfood docs [meta]

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#262]
Tracking bug for all the docs that need wrangling for fishfood.

  * [x] create or repurpose an alpha doc README #261
  * [x] document how to install the plugin #255
  * [x] migrate user journeys to a separate doc in docs/ #265 
  * [x] link to the docs/readme from the README #264

...

Please add more to the punch-list!

/cc @mit-mit @devoncarew
