### ISSUE TITLE
Meta-issue: Support updating code with hot reload while debugging

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#272]
The ability to update the source code while stopped at a breakpoint is really powerful. However, the may cause the breakpoint locations to move, and thus the VM needs to be told what the new breakpoint locations are.

Work items:

  - [ ] document deamon protocol: #273 
  - [ ] IntelliJ tracking and communication of new breakpoints
  - [ ] VM support for new deamon protocol

**Comment by mit-mit** [comment]
Closing this in favor of just tracking this with 305.
