### ISSUE TITLE
Support for viewing and running Flutter documentation code samples

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2968]
A meta-issue to track sample creation (e.g., `flutter create -sample`) and execution from the IDE.

### Flutter

  - [x]  support for enumerating template sample ids https://github.com/flutter/flutter/issues/25461
    - [x] PR: https://github.com/flutter/flutter/pull/25515

### IDEA / IntelliJ

  - [x] support for creating sample content in the New Project Wizard (IDEA) #2974 
  - [x] support for creating sample content in the New Project Wizard (Android Studio) #2975
  - [x] banner notifications for source files containing runnable samples (IDEA) #2976
    - [x] (in Android Studio) #3143

### VSCode

  - [x] support creating Flutter docs sample applications  (meta) https://github.com/Dart-Code/Dart-Code/issues/1356

**Comment by DanTup** [comment]
I've opened https://github.com/Dart-Code/Dart-Code/issues/1356 for the VS Code work.

**Comment by pq** [comment]
Besides being able to generate sample content from the new project wizard (which I expect could have a UI similar to the way we support stagehand templates), we should explore other ways to surface samples.  Existing dartdoc support is a little basic so it's not obvious what we can do there without a bunch of work on the Dart Plugin, but we should consider it?  For example, here's the "quick documentation" view for `AppBar` which has an associated sample.

![image](https://user-images.githubusercontent.com/67586/50125620-9135b000-021e-11e9-94be-e54c3e584613.png)

There could be a link or some kind of affordance to create a sample from the docs.  (The question remains though if anyone would find it since I'm not sure how well used that view is...)

/cc @jacob314 @InMatrix 

@alexander-doroshko : do you have any analytics on how used the quick doc view is?

**Comment by pq** [comment]
Ah, and here's a mock of how sample creation from the new wizard might look:

![image](https://user-images.githubusercontent.com/67586/50125460-e1604280-021d-11e9-814d-423c5d4ce956.png)

**Comment by InMatrix** [comment]
> (The question remains though if anyone would find it since I'm not sure how well used that view is...)

My impression is Quick Documentation a little bit hard to discover by users new to IntelliJ. In contrast, VS Code shows Quick Documentation anytime the mouse cursor is on a class name or method name.

I suspect we need to provide two entry points for running sample code in API docs: one from Flutter's API references on docs.flutter.io, and another one from within the IDE when the user checks documentation in the source code. For the latter, maybe the IDE can show a banner notification when the source file contains a runnable sample?

**Comment by DanTup** [comment]
> For the latter, maybe the IDE can show a banner notification when the source file contains a runnable sample?

For VS Code, if https://github.com/Microsoft/vscode/issues/65269 gets fixed, then rather than potentially spamming with banners, we could inject links into the hovers that say "Open sample in VS Code", that when clicked will spawn a new VS Code window that automatically downloads the sample ready to run. I think that could be a nice experience?

**Comment by InMatrix** [comment]
Sounds good to me, @DanTup.

**Comment by DanTup** [comment]
I tested out the VS Code protocol handler, and the rest of it works great. For ex. if https://github.com/Dart-Code/Dart-Code/pull/1358 is landed, we can link to `vscode://Dart-Code.dart-code/flutter/sample/material.AppBar.actions` (both on the web  and hopefully in hovers if the bug above is fixed) and it'll create the sample project (similar to how `Flutter: New Project` works).

If we get the ability to enumerate the full list, I can also add in a command that lets you select one.

**Comment by pq** [comment]
> I suspect we need to provide two entry points for running sample code in API docs: one from Flutter's API references on docs.flutter.io, and another one from within the IDE when the user checks documentation in the source code. 

Unfortunately, I don't think a protocol handler is straight-forward in IntelliJ (see e.g., https://youtrack.jetbrains.com/issue/IDEA-65879).   

Failing a one-click solution I suppose we could introduce an action that uses clipboard content and then the flow could be:

1. copy id to clipboard (in browser)
2. invoke "Create sample from clipboard..." action (in IDEA)

🤔

@alexander-doroshko: any thoughts or experience here?

> For the latter, maybe the IDE can show a banner notification when the source file contains a runnable sample?

A banner in IntelliJ I think this is a great idea. 👍

**Comment by alexander-doroshko** [comment]
I don't think IDEA-65879 is directly related. Are you thinking about links handling in Quick Doc popup? `ExternalDocumentationHandler.handleExternalLink()` allows doing that. what do you want to happen on click?

> the source file contains a runnable sample

What does it technically mean?
And what does a 'sample' mean: a piece of code, a single file or a bunch of files?

**Comment by pq** [comment]
@alexander-doroshko: we're talking about support for url handling so that you could click a link, for example, in chrome (not quick docs) where you're browsing for example https://docs.flutter.io/flutter/material/IconButton-class.html and have a new project created in the IDE.

> What does it technically mean?
> And what does a 'sample' mean: a piece of code, a single file or a bunch of files?

If you look at the IconButton class [docs](https://docs.flutter.io/flutter/material/IconButton-class.html), you'll see:

![image](https://user-images.githubusercontent.com/67586/50158849-10140280-028a-11e9-86b1-dad9eca0e0aa.png)

The Flutter `create` command supports the creation of apps with sample content.  This issue is about integrating that support into the IDE.

**Comment by pq** [comment]
As of #3143, MVP support is complete. Let's track ongoing polish in follow-up issues.

Thanks all! 👍
