### ISSUE TITLE
log error UI punchlist

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#3139]
Error UI punch-list (following up from https://github.com/flutter/flutter-intellij/pull/3138):

- [x] add hyperlink support to stack traces
- [x]  link node selections to inspector
- [x]  auto scroll-to-top of error pane
- [ ] auto-expand nodes (to one level)
- [ ]  dark-theme improvements / awareness
- [ ]  styling in general

**Comment by devoncarew** [comment]
Is this necessary or planned for M35?

**Comment by terrylucas** [comment]
M36?

**Comment by devoncarew** [comment]
Closing, and we can track logging view improvements in more granular issues.
