### ISSUE TITLE
P0: IntelliJ can create, launch, connect and inspect a FlutterWeb app (a webdev based workflow)

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#3293]
@jwren, this covers a few more items then just launching the apps. We can add additional issues if we want more granularity.

Current status (as of March 27th):

- [x] Add code to determine if some Flutter project is a Flutter Web project, done with https://github.com/flutter/flutter-intellij/commit/aafadf8c2a32ff3ad6d89e49d6e5b45d2fd88dd2
- [x] Modify the flutter run configuration to work with a null device, if a FlutterWeb- done with https://github.com/flutter/flutter-intellij/pull/3315- [ ] Have the WebSocket connect, currently blocked by https://github.com/dart-lang/webdev/issues/233
- [x] After the WebSocket connection is established, test that any protocol calls that aren't supported (or ignored) aren't sent from Flutter IntelliJ
- [x] remove the `FlutterCommand.localWebDevExe` field and associated code, test that the command line from FlutterSdk.flutterRunWeb works, https://github.com/flutter/flutter-intellij/issues/3348
- [x] Stagehand support- test that the generated samples for FlutterWeb work in the Flutter IntelliJ plugin
- [ ] provision webdev on the user's machine
- [x] ensure that the inspector works

**Comment by jwren** [comment]
https://github.com/flutter/flutter-intellij/pull/3315

**Comment by jwren** [comment]
Current status (March 27th):

- [x] Add code to determine if some Flutter project is a Flutter Web project, done with https://github.com/flutter/flutter-intellij/commit/aafadf8c2a32ff3ad6d89e49d6e5b45d2fd88dd2
- [x] Modify the flutter run configuration to work with a null device, if a FlutterWeb- done with https://github.com/flutter/flutter-intellij/pull/3315- [ ] Have the WebSocket connect, currently blocked by https://github.com/dart-lang/webdev/issues/233
- [ ] After the WebSocket connection is established, test that any protocol calls that aren't supported (or ignored) aren't sent from Flutter IntelliJ
- [ ] After the webdev lands in the Dart SDK in the Flutter SDK, remove the `FlutterCommand.localWebDevExe` field and associated code, test that the command line from FlutterSdk.flutterRunWeb works.
- [ ] Stagehand support- test that the generated samples for FlutterWeb work in the Flutter IntelliJ plugin

**Comment by devoncarew** [comment]
Awesome, thanks for the update and checklist!

**Comment by jwren** [comment]
The original PR, #3315 was reverted due to a bug introduce to normal flutter run debugging, https://github.com/flutter/flutter-intellij/pull/3342 fixes that issue.
