### ISSUE TITLE
Tracking issue for add-to-app

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#3554]
There are some things that need to be done in Android Studio to support add-to-app. Some of these may be applicable to IntelliJ.
- **Phase 1**
- [ ] Update the new project wizard to allow language choice on the last page.
- [ ] Add UI affordance to support continuously re-connecting the Android app during Flutter hot reload. https://github.com/flutter/flutter/issues/32824
- [ ] Add UI affordance to trigger Flutter build. https://github.com/flutter/flutter/issues/26099
- [ ] Propagate run mode (profile, debug) to attach command. https://github.com/flutter/flutter/issues/32999
- [ ] Add entry-point to run configurations. https://github.com/flutter/flutter/issues/31490
- [ ] Add support for `flutter integrate` to existing Flutter module in AS. Currently it only hooks in include_flutter.groovy. https://github.com/flutter/flutter/issues/32993
- [ ]  Launch devtools from Flutter attach button. (Are we sure we want to do this when we already have a button for it?) https://github.com/flutter/flutter/issues/33001
- [ ]  Integration tests for IDE extensions. https://github.com/flutter/flutter/issues/33144

- **Phase 2**
- [ ] Investigate re-use of AS resource management to support use of Android resources by Flutter modules. https://github.com/flutter/flutter/issues/31501
- [ ] Doing the inverse (access Flutter resources in Android code) would require changes to the Android Studio code base.
- [ ] Add a custom Project Structure editor to manage all of pubspec.yaml. (Once again.)

- **Phase 3**
- [ ] Investigate possibility of adding support for Flutter modules to AS Project Structure editor (may require changing AS code base).

- **Phase 4**
- [ ] Investigate possibility of editing Flutter code as part of an Android project (requires changes to AS code base).
- [ ] Index C++ code and support library management -- might be free if previous item is implemented.

@devoncarew @xster

**Comment by xster** [comment]
> Add UI affordance to support continuously re-connecting the Android app during Flutter hot reload. flutter/flutter#32824

nit: this would be for all device types where it makes sense

**Comment by stevemessick** [comment]
It may not be related, but https://github.com/flutter/flutter-intellij/issues/1369 might be good to keep in mind while doing this work.
