### ISSUE TITLE
Add-to-app release features

### ISSUE THREAD

**Issue by xster** [flutter/flutter-intellij#4064]
Extracting some discussion items out of #3554 for release tracking.

- [x] Let the AndroidX setting follow the parent project's AndroidX setting **P1**
- [x] Just do include_flutter.groovy for now **P1**
- [x] The auto integration probably needs to add compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    } to the host app's build.gradle too **P1** #4134
- [x] Resurface the flutter attach button in the toolbar **P1**
- [x] Let the user choose the directory when creating new modules **P2** #4134
- [x] Choose the debug/profile/release mode of the AAR built when building an AAR from the menu ** P2 ** Done via https://github.com/flutter/flutter/pull/44797
- [x] If only one Flutter fun config exists then the Flutter attach button is active even if it is not selected **P2** #4134

And when https://github.com/flutter/flutter/issues/32999 makes it in:

- [x] Let flutter attach monitoring start as soon as the Android host app is launched to allow hot reload on Dart file save when the user navigates into the Flutter screen. **P2**

**Comment by devoncarew** [comment]
@stevemessick, should we break these out into individual issues? That may be helpful if some items have different priority, and or may land in different releases.

**Comment by xster** [comment]
Thanks. Commented inline.

**Comment by stevemessick** [comment]
Thanks @xster, that helps.

**Comment by xster** [comment]
One more note that @matthew-carroll just noticed. It would be nice (for Flutter modules in general) to be able to choose the debug/profile/release mode of the AAR built when building an AAR from the menu (might already be possible?). P2

**Comment by stevemessick** [comment]
I added that to #4064

**Comment by xster** [comment]
Thanks for the demo plugin @stevemessick 

I tried it a bit. It's much smoother than the last one. A few more observations

- In the outer app's settings.gradle, `include ':flutter_module'` appeared multiple times, though it's probably inconsequential

![Screen Shot 2019-11-18 at 6 19 58 PM](https://user-images.githubusercontent.com/156888/69111711-3c547800-0a33-11ea-8ca4-7743c9ad4466.png)

- The Java 8 compileOptions wasn't added in the outer app's build.gradle. The build fails to compile until added manually

- The Flutter attach is waiting for a service connection even though the Flutter screen already launched 

![Screen Shot 2019-11-18 at 6 40 42 PM](https://user-images.githubusercontent.com/156888/69111825-981f0100-0a33-11ea-9a46-3560ade76ae0.png)

Perhaps the IDE side work-around for Flutter attach on Android had some full-Flutter specific assumptions in it. Either way @blasten's generic flutter_tools side fix for Flutter attach seems like it'll be in momentarily https://github.com/flutter/flutter/pull/44637

- I had to switch the build configuration from the Android build target to the Flutter build target in order for the Flutter attach menu and toolbar options to be come enabled. 
![Screen Shot 2019-11-18 at 6 40 59 PM](https://user-images.githubusercontent.com/156888/69111870-b71d9300-0a33-11ea-9ae6-04070ae6038c.png)

Is there a way to have it always available as long as there is a Flutter build configuration present?

Thanks so much!

**Comment by stevemessick** [comment]
Glad you were able to use that plugin @xster.

> In the outer app's settings.gradle, include ':flutter_module' appeared multiple times, though it's probably inconsequential

I'm planning to clean that up. Thanks for the reminder.

> The Java 8 compileOptions wasn't added in the outer app's build.gradle. The build fails to compile until added manually

I wonder what we're doing differently? I always get this:
```groovy
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
I can add a check to ensure it is included.

> The Flutter attach is waiting for a service connection even though the Flutter screen already launched

I think the `flutter attach` has to occur before launching the Android app, at least with the sample code I use. I just created a sample Android app and Flutter module. Here's a screenshot of stopping at the canonical breakpoint:
<img width="1400" alt="Screen Shot 2019-11-19 at 9 11 30 AM" src="https://user-images.githubusercontent.com/8518285/69169148-b543e600-0aac-11ea-8173-dc1b57a1a175.png">

I'll take another look once flutter/flutter#44637 lands.

> I had to switch the build configuration from the Android build target to the Flutter build target in order for the Flutter attach menu and toolbar options to be come enabled.

Yeah, that's WAI but your suggestion sounds like a better way to do it. Shouldn't be difficult.

Thanks again for the feedback!

**Comment by stevemessick** [comment]
> Yeah, that's WAI but your suggestion sounds like a better way to do it. Shouldn't be difficult.

Oops, I forgot that the run config is actually used in the `flutter attach`. We get the command-line options from it. You could have multiple Flutter run configs to do different things and we need to know which one to use. So I think this needs to stay as it is.

**Comment by xster** [comment]
> I wonder what we're doing differently? I always get this:

I used the new Flutter module rather than import Flutter module if that makes a difference. 

https://github.com/flutter/flutter/pull/44637 is now merged (though temporarily reverted, but it should go back soon. You can just check out a32fc986f directly too). 

Flutter attach now connects correctly either before launching the Android app or after :D

It did surface one change I think we should make. For the CLI, I'm attaching a small video to demonstrate. 

https://streamable.com/waxnw

The behavior we'd want is for the attach session to be persistent across app relaunches until the user explicitly decides to disconnect. It works in the CLI, but the IntelliJ plugin and VSCode currently disconnects permanently once the app closes. Could we keep it alive?

> Oops, I forgot that the run config is actually used in the flutter attach.

Is there a way for the plugin to detect that only a single Flutter config exists, if so, then default to that one? If multiple Flutter config exists, then we can ask the user to select one but that should be rare.

**Comment by xster** [comment]
Mirror issue for the attach on VSCode https://github.com/Dart-Code/Dart-Code/issues/2115
