### ISSUE TITLE
august-1 meta issue

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#53]
- [x] testing (automated; unit tests; #30, #66, #96)
- [ ] project creation flow
- [x] better clarity on how we distribute the plugin (versioning issues w/ the Dart plugin; building against the last stable IntelliJ API)
- [ ] determine the user flows we'll use to guide our initial development (project creation to hitting a breakpoint; opening an existing project on disk to hitting a breakpoint) (https://github.com/flutter/flutter-intellij/wiki/User-Journeys)
- [ ] write a manual testing script; to be maintained as we add features

**Comment by devoncarew** [comment]
Closing; we have a new demo milestone.
