### ISSUE TITLE
UX punchlist

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#730]
This is a list of items from a recent UX study and items found from smoke-testing; writing this down so I don't forget:

- [ ] flutter tools initialization - this can be slow if flutter tools is downloading artifacts in the background
  - [ ] create and pass in a --no-download-cache flag
  - [ ] daemon mode should not grab the flutter tools lock
- [ ] show `flutter create` progress in a progress job (we shouldn't open a message panel at all; it fights with the analysis view) (https://github.com/flutter/flutter-intellij/issues/734)
- [ ] show a toast when the project create is finished (https://github.com/flutter/flutter-intellij/issues/734)
- [ ] show "All done!" in bold on the CLI
- [x] ios simulator output should be cleaned up - it's very verbose (https://github.com/flutter/flutter/issues/2346)
- [ ] we should pre-populate the tool window setup info (https://github.com/flutter/flutter-intellij/issues/735)
- [ ] show errors in the toolbar (https://github.com/flutter/flutter-intellij/issues/732)
- [x] hitting return in a line comment in the newly created flutter project template file indents in the wrong place (https://github.com/flutter/flutter-intellij/issues/767)
- [x] revert the *.iml file location change (https://github.com/flutter/flutter-intellij/issues/714)
- [x] can we show tooltips in the editor butter bar? this is to address confusion over the difference between `packages get` and `packages upgrade` (https://github.com/flutter/flutter-intellij/issues/733)
- [x] Colors.lightBlue doesn't show up (it's a map; try 400 if none set)
- [ ] auto-expressions in the debugger would help a lot (https://youtrack.jetbrains.com/issue/WEB-12233)
- [ ] show a notification on a run (or reload) if there are analysis issues (https://github.com/flutter/flutter-intellij/issues/729)
- [x] add the hot reload actions to the Run menu

**Comment by eseidelGoogle** [comment]
There are several other bugs (including other proposals) like https://github.com/flutter/flutter/issues/6491 about your first issue.  Possible commands which don't need artifacts shouldn't prompt their download at all. :)

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/2582 may also be related to the long-pause question (I think there may also be a bug for `flutter create` too).

**Comment by eseidelGoogle** [comment]
iOS Simulator output: https://github.com/flutter/flutter/issues/2346

**Comment by eseidelGoogle** [comment]
Colors usability: https://github.com/flutter/flutter/issues/6706

**Comment by devoncarew** [comment]
closing in favor of more specific issues
