### ISSUE TITLE
M12 plan

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#818]
This is the plan for the M12 milestone.

### Editing
- [x] Code completion should insert placeholders for `@required` parameters #553 @pq
- [x] Add default arg "smart insert" configurability to the Dart Plugin #831 @pq
- [x] Assist converting child: to children: #819 @stevemessick
- [x] Quick-fix to convert child: to children: #820 @stevemessick
- [x] Insufficient warning when the build function doesn't return a widget #808 @pq
- [x] Add templates for common boilerplate #800 @stevemessick

### Testing and infra
- [x] support 2017.1 #823 @devoncarew

## Releasing
The release date is March 28th (Tuesday).

(testing [script](https://github.com/flutter/flutter-intellij/blob/master/testing.md) )

- [x] update change notes @pq (#837)
- [x] create candidate build, March 27th (Monday) @pq
- [x] run test script on internal build @skybrian 
- [x] run test script on IntelliJ CE (2016.3) @pq
    - [x] tested against 4129829d8a005e04a74bd6e39532ead5386855c5 👍 
- [x] run test script on IntelliJ CE windows @mit-mit 
- [x] run test script on WebStorm @devoncarew
- [x] publish plugin ([done](https://plugins.jetbrains.com/plugin/9212-flutter))
- [x] send blog post @mit-mit 

---

## Deferred
- Insert a child: (or children: list) placeholder for Widgets on code completion #463 @pq (upstream changes in flight)
- show analysis issues on app run #729 @devoncarew (upstream changes landed)
- re-enable unit testing on the bots #726 @devoncarew
- investigate FEST for integration tests #817 @devoncarew
- Fix breakpoints when running on mac bazel #784 @skybrian 
- re-examine our hot reload keybinding #751

**Comment by devoncarew** [comment]
@mit-mit, @skybrian, can you update your testing bit above?

**Comment by mit-mit** [comment]
Completed my testing, and found a number of issues (incl. several that I think are release blocking)

**Comment by mit-mit** [comment]
Announced:
https://groups.google.com/forum/#!msg/flutter-dev/Og4JDrNbbQY/gxuqZnYtAwAJ
https://plus.google.com/b/104717055236045741163/+FlutterIo/posts/hBzRER7ixNF
