### ISSUE TITLE
M13 plan

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#854]
This is the plan for the M13 milestone.

### Editing
- [x] color indicator in gutter doesn't work with new short color syntax #866 @devoncarew
- [x] Rename wrap assist to 'Wrap with new widget' #889 @messick
- [x] fix text indent for existing named params #792

### Run and debug
- [x] expose an action to toggle the platform OS for a running Flutter app
- [x] make it clearer to developers when and how to hot reload vs restart #803 @devoncarew
- [x] expose --release and --profile modes #410 @pq
- [x] add drop frame support while debugging
- [x] simplifications to the launch configuration dialog for bazel #643 @skybrian

### Getting started and plugins support
- [x] verify the Flutter plugin works with a separate SDK than web Dart projects #822
- [x] support editing a Flutter project's Android java code in IntelliJ IDEA #782 @skybrian 

### Infra
- [x] convert plugin to fully 2017.1 #861 @devoncarew
- [x] when invoking the flutter tool, we should pass in a marker env variable #840 @devoncarew

## Releasing
The release date is April 19th (Wednesday).

- [x] update change notes @pq
- [x] create candidate build, April 18th (Monday) @pq
- [x] testing ([script](https://github.com/flutter/flutter-intellij/blob/master/testing.md)):
  - [ ] run test script on internal build @skybrian 
  - [x] run test script on IntelliJ CE @pq
  - [x] run test script on IntelliJ CE windows @mit-mit 
  - [x] run test script on WebStorm @devoncarew
- [x] update our hosted docs (there are several UI changes) @mit-mit
- [x] publish plugin
- [x] send blog post @mit-mit 

---

## Deferred
- [ ] show analysis issues on app run #729 @devoncarew
- [ ] completions on named arguments should include trailing comma #551 @pq
- [ ] enable starting an Android emulator from IntelliJ like we do for iOS #536 - _blocked_
- [ ] reexamine our hot reload keybinding #751 @devoncarew (some progress, more work planned)
- [ ] insert a `child:` (or `children:` placeholder list) for Widgets on code completion #463 @pq
- [ ] still breaking at removed breakpoint #790
