### ISSUE TITLE
M14 plan

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#925]
This is the plan for the M14 milestone.

### Editing
- [x] completions on named arguments should include trailing comma #551 @pq 
- [x] insert a child: (or children: placeholder list) for Widgets on code completion #463 @pq

### Run and debug
- [x] move the reload button in the toolbar next to the run/debug/stop buttons
- [x] hot reload doesn't work when stopped at a breakpoint #969
- [x] still breaking at removed breakpoint #983 

### Getting started
- [x] research approaches to android emulator interop #923
- [x] validate module names during creation #609 @pq 
- [x] improved the progress display when creating projects
- [x] unable to open /flutter/examples without issues in 2017.1 #860 @skybrian 

### Android
- [x] setting Android SDK in IDE overrides ANDROID_HOME variable
- [x] on project open, automatically set project's Android SDK to ANDROID_HOME if unset

### Diagnostics
- [x] adding a diagnostic logging (verbose) mode

## Releasing
The release date is May 18th (Thursday).

- [x] update change notes @pq
- [x] create candidate build, May 16th (Tuesday) @pq
- [ ] testing ([script](https://github.com/flutter/flutter-intellij/blob/master/testing.md)):
  - [ ] run test script on internal build @skybrian 
  - [x] run test script on IntelliJ CE @pq
  - [x] run test script on IntelliJ CE windows @mit-mit 
  - [x] run test script on WebStorm @devoncarew
- [x] publish plugin
- [ ] send blog post @mit-mit 

---

## Deferred
- [ ] investigate FEST for integration tests #817
- [ ] re-enable unit testing on the bots #726
- [ ] fix and re-enable launching in profile mode #930
- [ ] define the IntelliJ getting started workflow

**Comment by mit-mit** [comment]
No issues found during windows testing!
